# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_serialize"
version = "0.3.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Serializing various CLInvoice entities"

edition = "2018"
license = "GPL3"
readme = "../README.md"
repository = "https://www.github.com/Iron-E/clinvoice"

[dependencies]
# CLInvoice
clinvoice_data = {path='../clinvoice_data', version="0.5"}
clinvoice_error = {path='../clinvoice_error', version="0.2"}

# Errors
thiserror = "1"

[features]
default = ["markdown"]
markdown = []
